ATIVIDADE 01

public class Atividade  {
    public static void main(String[] args) {

   String  nome = "ANA"; // caracter
   String  sobrenome= "Silveira"; // caracter texto sempre aspas duplas
   String  cidade = "Francisco Beltrao" ;  
   String  estado = "Parana" ;
   String mes = "Agosto" ;
   int idade = 25;
   Integer ano = 98 ;
   double peso = 64.5;
   boolean confirma = true ;
   char sexo = 'F'; 
}
}

ATIVIDADE 02

public class HelloWorld {
    public static void main(String[] args) {

 // 2 Corrija os erros de nomenclatura do padrão camelCase e crie no java.  
1. nomeDoProduto
2. preçoProduto
3. marcaDoProduto
4. quantidadeProduto
5. descricaoProduto
6. nomeProduto
7. numeroProduto
8. precoDoProduto
9. estoqueDisponivel
10. totalDeProdutos
}

ATIVIDADE 03
public class Atividade  {
    public static void main(String[] args) {

String  nomeDoAluno = "ANA"; // caracter
int idadeDoAluno = 25;
double notaDaProva1 = 9.5;
double notaDaProva2 = 8.2;
double mediaFinal= 8.85;
    }
    
}
