ATIVIDADE 01

public class Atividade  {
    public static void main(String[] args) {

   String  nome = "ANA";
   String  sobrenome= "Silveira";
   String  cidade = "Francisco Beltrao" ;  
   String  estado = "Parana" ;
   String mes = "Agosto" ;
   int idade = 25;
   Integer ano = 98 ;
   double peso = 64.5;
   boolean confirma = true ;
   char sexo = 'F'; 
}
}

ATIVIDADE 02

public class HelloWorld {
    public static void main(String[] args) {

 // 2 Corrija os erros de nomenclatura do padrão camelCase e crie no java.  
1. nomeDoProduto
2. preçoProduto
3. marcaDoProduto
4. quantidadeProduto
5. descricaoProduto
6. nomeProduto
7. numeroProduto
8. precoDoProduto
9. estoqueDisponivel
10. totalDeProdutos
}

ATIVIDADE 03
public class Atividade  {
    public static void main(String[] args) {

String  nomeDoAluno = "ANA";
int idadeDoAluno = 25;
double notaDaProva1 = 9.5;
double notaDaProva2 = 8.2;
double mediaFinal= 8.85;
    }
    
}

ATIVIDADE 04

public class ControleEstoque {
    public static void main(String[] args) {
     
String nomeProduto;
String categoriaProduto;
double precoProduto;
int quantidadeProduto;

    }
   
}  

ATIVIDADE 05

public class Main {
    public static void main(String[] args) {

       int numeroSmartphone = 12 ; 
       double precoSmartphone = 2100.00; 
       String descricaoSmartphone = "Smartphone";
       String dadosDoSmartphone = "Xiaomi" ;
        
       int numeroLaptop= 13 ; 
       double precoLaptop = 4500.00; 
       String descricaoLaptop = "Laptop";
       String dadosDoLaptop = "Dell" ;
       
       int numeroFone= 14 ; 
       double precoFone = 250; 
       String descricaoFone = "Fone de Ouvido";
       String dadosDoFone = "JBL" ;
       
        
        
       System.out.println("Informacoes sobre Smartphone:");
        
        System.out.println("Dados do Produto: "+ dadosDoSmartphone);
        System.out.println("Numero: " + numeroSmartphone);
        System.out.println("Preco: $" + precoSmartphone);
        System.out.println("Descricao: " + descricaoSmartphone);
        System.out.println();
        
       System.out.println("Informacoes sobre Laptop:");
        
        System.out.println("Dados do Produto: "+ dadosDoLaptop);
        System.out.println("Numero: " + numeroLaptop);
        System.out.println("Preco: $" + precoLaptop);
        System.out.println("Descricao: " + descricaoLaptop);
        System.out.println();
        
       System.out.println("Informacoes sobre Fone de Ouvido:");
        
        System.out.println("Dados do Produto: " + dadosDoFone);
        System.out.println("Numero: " + numeroFone);
        System.out.println("Preco: $" + precoFone);
        System.out.println("Descricao: " + descricaoFone);
    } 
}

ATIVIDADE 06

public class Main {
    public static void main(String[] args) {
       
        String numeroProduto = "ABC123" ; 
        double precoProduto = 25; 
        String descricaoProduto = "Fone de Ouvido Bluetooth" ;
        
         descricaoProduto = "Fone de ouvido Bluetooth" ;
         
        System.out.println("Descricao do Produto: " + descricaoProduto);
        System.out.println("Dados do Produto:");
        System.out.println("Numero: " + numeroProduto);
        System.out.println("Preco: $ " + precoProduto);
        System.out.println("Descricao: " + descricaoProduto);
    }
}

ATIVIDADE 07

public class ControleEstoque {
    public static void main(String[] args) {
     
        String nomeProduto= "Fone de Ouvido";
        int dadosDoProduto= 12345;
        boolean marcaProduto= true;
        double precoProduto= 29.99;
        int quantidadeProduto= 10;
        
        
        
        System.out.println("Dados do Produto: " + dadosDoProduto);
        System.out.println("Nome: " + nomeProduto);
        System.out.println("Marca: " + marcaProduto);
        System.out.println("Preco: $ " + precoProduto);
        System.out.println("Quantidade em estoque: " + quantidadeProduto);
    }
}

ATIVIDADE 08 

Os capítulos lidos conforme solicitados, ressaltam a importância de existir programadores pro trás dos códigos e também a forma de como eles são organizados. Cita também
sobre a importância de manter um código bem estruturado, limpo e organizado para de fato ter bom entendimento, não só própio de quem o criou, mas para caso acessado
por outros programadores, seja de fácil manutenção.
